name: coroot

volumes:
  prometheus_data: {}
  clickhouse_data: {}
  clickhouse_logs: {}
  coroot_data: {}
  simulator_data: {}
  node_agent_data: {}
  cluster_agent_data: {}

services:
  coroot:
    restart: always
    # image: ghcr.io/coroot/coroot${LICENSE_KEY:+-ee} # set 'coroot-ee' as the image if LICENSE_KEY is defined
    pull_policy: never
    user: root
    volumes:
      - coroot_data:/data
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command:
      - '--data-dir=/data'
      - '--bootstrap-prometheus-url=http://prometheus:9090'
      - '--bootstrap-refresh-interval=15s'
      - '--bootstrap-clickhouse-address=clickhouse:9000'
    environment:
      - LICENSE_KEY="COROOT-D09B116E-83CF-4385-B51C-CF46507D4A1A"
      - PROMETHEUS_REMOTE_WRITE_URL=http://prometheus:9090/api/v1/write
    depends_on:
      - clickhouse
      - prometheus
      
  springboot-exception-simulator:
    build:
      context: ../springboot-exception-simulator
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    user: root
    volumes:
      - simulator_data:/var/log/simulator
    environment:
      - JAVA_OPTS=-XX:+PreserveFramePointer -Xms256m -Xmx512m -javaagent:/app/opentelemetry-javaagent.jar   
      - OTEL_SERVICE_NAME="java" 
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="http://13.49.159.64:8080/v1/traces" 
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT="http://13.49.159.64:8080/v1/logs" 
      - OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf" 
      - OTEL_METRICS_EXPORTER="none" 
      - OTEL_EXPORTER_OTLP_HEADERS="x-api-key=LNNcSb6Y4OU2akp4OOP0Gn9IGMkKQZVO"
    depends_on:
      - coroot 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"    

  # node-agent:
  #   restart: always
  #   image: ghcr.io/coroot/coroot-node-agent
  #   pull_policy: always
  #   privileged: true
  #   pid: "host"
  #   volumes:
  #     - /sys/kernel/tracing:/sys/kernel/tracing
  #     - /sys/kernel/debug:/sys/kernel/debug
  #     - /sys/fs/cgroup:/host/sys/fs/cgroup
  #     - node_agent_data:/data
  #   command:
  #     - '--collector-endpoint=http://coroot:8080'
  #     - '--cgroupfs-root=/host/sys/fs/cgroup'
  #     - '--wal-dir=/data'

  # cluster-agent:
  #   restart: always
  #   image: ghcr.io/coroot/coroot-cluster-agent
  #   pull_policy: always
  #   volumes:
  #     - cluster_agent_data:/data
  #   command:
  #     - '--coroot-url=http://coroot:8080'
  #     - '--metrics-scrape-interval=15s'
  #     - '--metrics-wal-dir=/data'
  #   depends_on:
  #     - coroot

  prometheus:
    restart: always
    image: prom/prometheus:v2.53.5
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    ports:
      - '127.0.0.1:9090:9090'

  clickhouse:
    restart: always
    image: clickhouse/clickhouse-server:24.3
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: "1"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ports:
      - '127.0.0.1:9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
